# Generated by Django 5.2.17 on 2026-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Pay with Card'), ('paypal', 'Paypal')], default='card', max_length=20),
        ),
    ]
