# Generated by Django 5.2.17 on 2026-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_address_user_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_color_options',
            field=models.BooleanField(default=False),
        ),
    ]
