# Generated by Django 5.2.17 on 2026-09-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productimage_options_productimage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
