# Generated by Django 5.2.17 on 2026-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_size_options',
            field=models.BooleanField(default=False),
        ),
    ]
